Add support for Laravel 8
awssat/laravel-visits pull request #59
Opened 2020-09-10 18:47 UTC by adriaanzon

2020-09-10 18:57 UTC, adriaanzon commented
Laravel 8 dropped support for PHP 7.2. You may want to remove it from the matrix or set up a separate metric that doesn't include PHP 7.2.

2020-09-12 10:57 UTC, if4lcon requested changes

2020-09-12 10:57 UTC, if4lcon commented on composer.json
>          "php": "^7.2",
php 7.3  ?

2020-09-12 10:57 UTC, if4lcon commented on composer.json
>          "phpunit/phpunit": "^8.5",
also this we might bump it to version 9

2020-09-12 10:57 UTC, if4lcon commented on .github/workflows/run-tests.yml
>                  php: [7.2, 7.3, 7.4]
we need to ditch php 7.2

2020-09-13 16:44 UTC, adriaanzon commented on composer.json
>          "php": "^7.2",
While removing support for 7.2 would not be strictly necessary because applications using older versions of Laravel could still be on 7.2, I think it's fair to remove it here, also given the fact that it will reach end of life in a few months.

2020-09-13 18:35 UTC, abdumu approved these changes

2020-09-13 21:33 UTC, merged

2020-11-11 02:09 UTC, valascus commented
torann/geoip also needs to be updated